# Site settings
title: Thought.out.printf()
#email: your-email@domain.com

description: > # this means to ignore/fold newlines until "baseurl:"
  Becoming a literate scientific developer, building common understanding.
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://renzok.github.io" # the base hostname & protocol for your site

twitter_username: renzokott

github_username:  renzok

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

gems:
  - jekyll-redirect-from

collections:
  slides:
    output: true
  style-rules:
    output: true
    permalink: /gtkme/styles/:categories/:slug
  lecture:
    output: true  
    
defaults:
  - scope:
      path: ""
      type: style-rules
    values:
      layout: rule
      author: Renzo Kottmann
      
