# Site settings
title: Thought.out.printf()
#email: your-email@domain.com

description: > # this means to ignore/fold newlines until "baseurl:"
  Becoming a literate scientific developer, building common understanding.
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://renzok.github.io" # the base hostname & protocol for your site

twitter_username: renzokott

github_username:  renzok

# Build settings
#markdown: kramdown

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

# deprectaed by github pages:
# redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]


collections:
  slides:
    output: true
  style-rules:
    output: true
    permalink: /gtkme/styles/:categories/:slug

defaults:
  - scope:
      path: ""
      type:
  - scope:
      path: ""
      type: style-rules
    values:
      layout: rule
      author: Renzo Kottmann
      
